title: "acid substances harm reduction"
summary: "for when u took psychedelics subtances accidentally"
topics: ["acid", "hr", "drug"]
published: true
price: 0
chapters:
  - introduction
  - whatsacid
  - whatsfor
  - kind
  - cleaning
  - trust
  - sitter
  - bad
  - music
  - foods
  - howtotake
